name: GoldenRural
favicon: null
layout_spectrum: 0.04447580827400088
typography_spectrum: 0.7564661500509828
title: Golden Rural High Speed Internet and more ...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.6867000681813806
  rhythmicContrast: 0.75
purpose: []
